"""MD parameter blocks copied from the inspectable integration-test workflow.

These dictionaries are kept in ``actions`` because they are grubicy workflow
settings, not core library defaults. Each step-specific runner imports exactly
one parameter block and passes it into ``GromacsParams`` before calling the
existing BioSimSpace/GROMACS helper. The values mirror the test workflow: SD,
CG, restrained NVT heating, restrained NPT, unrestrained NPT, and production.
Keeping them here avoids importing test modules from production workflow code.
"""

from __future__ import annotations

from typing import Any

SD_PARAMS: dict[str, Any] = {
    "integrator": "steep",
    "nsteps": 500000,
    "emtol": 100.0,
    "emstep": 0.001,
    "cutoff_scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "rlist": 1.221,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.16,
    "pme_order": 4,
    "ewald_rtol": 1e-5,
    "vdwtype": "Cut-off",
    "vdw_modifier": "Force-switch",
    "rvdw_switch": 1.0,
    "rvdw": 1.2,
    "constraints": "none",
    "tcoupl": "no",
    "pcoupl": "no",
    "gen_vel": "no",
    "nstlog": 500,
    "nstenergy": 500,
    "nstxout_compressed": 0,
}

CG_PARAMS: dict[str, Any] = {
    "integrator": "cg",
    "nsteps": 5000,
    "emtol": 100.0,
    "emstep": 0.001,
    "nstcgsteep": 50,
    "cutoff_scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "rlist": 1.221,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.16,
    "pme_order": 4,
    "ewald_rtol": 1e-5,
    "vdwtype": "Cut-off",
    "vdw_modifier": "Force-switch",
    "rvdw_switch": 1.0,
    "rvdw": 1.2,
    "constraints": "none",
    "tcoupl": "no",
    "pcoupl": "no",
    "gen_vel": "no",
    "nstlog": 500,
    "nstenergy": 500,
    "nstxout_compressed": 0,
}

HEATING_PARAMS: dict[str, Any] = {
    "integrator": "md",
    "dt": 0.001,
    "nsteps": 100000,
    "cutoff_scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "rlist": 1.221,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.16,
    "pme_order": 4,
    "ewald_rtol": 1e-5,
    "vdwtype": "Cut-off",
    "vdw_modifier": "Force-switch",
    "rvdw_switch": 1.0,
    "rvdw": 1.2,
    "constraints": "h-bonds",
    "constraint_algorithm": "LINCS",
    "lincs_order": 4,
    "lincs_warnangle": 30.0,
    "continuation": "no",
    "gen_vel": "yes",
    "gen_temp": 20.0,
    "tcoupl": "V-rescale",
    "tc_grps": "System",
    "tau_t": 0.1,
    "ref_t": 300.0,
    "pcoupl": "no",
    "annealing": "single",
    "annealing_npoints": 8,
    "annealing_time": "0 40.0 50.0 60.0 70.0 80.0 90.0 100.0",
    "annealing_temp": "20.0 50.0 100.0 150.0 200.0 250.0 300.0 300.0",
    "define": "-DPOSRES",
    "nstlog": 500,
    "nstenergy": 500,
    "nstcalcenergy": 100,
    "nstxout_compressed": 1000,
}

NPT_RESTRAINED_PARAMS: dict[str, Any] = {
    "integrator": "md",
    "dt": 0.002,
    "nsteps": 50000,
    "cutoff_scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "rlist": 1.221,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.16,
    "pme_order": 4,
    "ewald_rtol": 1e-5,
    "vdwtype": "Cut-off",
    "vdw_modifier": "Force-switch",
    "rvdw_switch": 1.0,
    "rvdw": 1.2,
    "constraints": "h-bonds",
    "constraint_algorithm": "LINCS",
    "lincs_order": 4,
    "lincs_warnangle": 30.0,
    "continuation": "yes",
    "gen_vel": "no",
    "tcoupl": "V-rescale",
    "tc_grps": "System",
    "tau_t": 0.1,
    "ref_t": 300.0,
    "pcoupl": "C-rescale",
    "pcoupltype": "isotropic",
    "tau_p": 5.0,
    "ref_p": 1.0,
    "compressibility": 4.5e-5,
    "refcoord_scaling": "com",
    "define": "-DPOSRES",
    "nstlog": 500,
    "nstenergy": 500,
    "nstcalcenergy": 100,
    "nstxout_compressed": 1000,
}

NPT_PARAMS: dict[str, Any] = {
    "integrator": "md",
    "dt": 0.002,
    "nsteps": 50000,
    "cutoff_scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "rlist": 1.221,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.16,
    "pme_order": 4,
    "ewald_rtol": 1e-5,
    "vdwtype": "Cut-off",
    "vdw_modifier": "Force-switch",
    "rvdw_switch": 1.0,
    "rvdw": 1.2,
    "constraints": "h-bonds",
    "constraint_algorithm": "LINCS",
    "lincs_order": 4,
    "lincs_warnangle": 30.0,
    "continuation": "yes",
    "gen_vel": "no",
    "tcoupl": "V-rescale",
    "tc_grps": "System",
    "tau_t": 0.1,
    "ref_t": 300.0,
    "pcoupl": "C-rescale",
    "pcoupltype": "isotropic",
    "tau_p": 5.0,
    "ref_p": 1.0,
    "compressibility": 4.5e-5,
    "define": "",
    "nstlog": 500,
    "nstenergy": 500,
    "nstcalcenergy": 100,
    "nstxout_compressed": 1000,
}

PRODUCTION_PARAMS: dict[str, Any] = {
    "integrator": "md",
    "dt": 0.002,
    "nsteps": 250000,
    "cutoff_scheme": "Verlet",
    "nstlist": 20,
    "pbc": "xyz",
    "rlist": 1.221,
    "coulombtype": "PME",
    "rcoulomb": 1.2,
    "fourierspacing": 0.16,
    "pme_order": 4,
    "ewald_rtol": 1e-5,
    "vdwtype": "Cut-off",
    "vdw_modifier": "Force-switch",
    "rvdw_switch": 1.0,
    "rvdw": 1.2,
    "constraints": "h-bonds",
    "constraint_algorithm": "LINCS",
    "lincs_order": 4,
    "lincs_warnangle": 30.0,
    "continuation": "yes",
    "gen_vel": "no",
    "tcoupl": "V-rescale",
    "tc_grps": "System",
    "tau_t": 0.1,
    "ref_t": 300.0,
    "pcoupl": "C-rescale",
    "pcoupltype": "isotropic",
    "tau_p": 5.0,
    "ref_p": 1.0,
    "compressibility": 4.5e-5,
    "define": "",
    "nstlog": 500,
    "nstenergy": 500,
    "nstcalcenergy": 100,
    "nstxout_compressed": 1000,
}
